name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake GIF and SVG
        uses: Platane/snk@v3
        with:
          github_user_name: hardiext
          output_branch: output
          gif_out_path: github-contribution-grid-snake.gif
          svg_out_path: github-contribution-grid-snake.svg
          palette: github-dark
          color_snake: "#ff4500"
          color_dots: "#161b22,#21262d,#30363d,#484f58"
