name: Generate Contribution Snake

# Run every 24 hours, allow manual run
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Generate GitHub contribution snake (SVG + dark mode)
      - name: Generate GitHub contribution snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3️⃣ Generate GitHub contribution snake GIF
      - name: Generate GitHub contribution snake GIF
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
          cell_size: 12   # optional, untuk menghindari GIF terlalu besar
          start_year: 2023
          end_year: 2025

      # 4️⃣ Debug: List files before pushing
      - name: List dist folder
        run: ls -R dist

      # 5️⃣ Push dist folder to output branch (GitHub Pages)
      - name: Push SVG and GIF to output branch
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: output
          build_dir: dist
          clean: false   # jangan hapus file lama di branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
