name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake GIF & SVG
        uses: Platane/snk@v3
        with:
          github_user_name: hardiext
          output_branch: output
          gif_out_path: github-contribution-grid-snake.gif
          svg_out_path: github-contribution-grid-snake.svg
          palette: github-dark
